# Image optimization (serve AVIF/WebP when available)
location ~* \.(?:jpe?g|png|webp|avif)$ {
    add_header Vary Accept;
    try_files $uri$dazestack_img_suffix $uri =404;
    expires 365d;
    add_header Cache-Control "public, immutable";
    access_log off;
}
