<?php

declare(strict_types=1);

namespace Tests\Unit\Seo;

use Helmetsan\Core\Seo\YoastSchemaAdapter;
use Helmetsan\Core\Seo\SchemaService;
use Helmetsan\Core\Seo\YoastSeoSeeder;
use Helmetsan\Core\Seo\AutoSeoObserver;
use Helmetsan\Core\Seo\SitemapEnhancer;
use Helmetsan\Core\Reviews\ReviewService;
use PHPUnit\Framework\TestCase;
use WP_Post;

final class YoastHarmonizationTest extends TestCase
{
    private SchemaService $schemaService;
    private YoastSchemaAdapter $schemaAdapter;
    private YoastSeoSeeder $seeder;
    private AutoSeoObserver $observer;

    protected function setUp(): void
    {
        parent::setUp();
        $GLOBALS['wp_mock_posts'] = [];
        $GLOBALS['wp_post_meta'] = [];
        $GLOBALS['wp_mock_singular_post_type'] = null;
        $GLOBALS['wp_mock_queried_object_id'] = 0;
        $GLOBALS['wp_mock_has_thumbnail'] = [];
        $GLOBALS['mock_helmetsan_core'] = null;
        $GLOBALS['wpdb'] = new class {
            public string $prefix = 'wp_';
            public function prepare(string $query, ...$args): string {
                return $query;
            }
            public function get_results(string $query, $output = 'OBJECT'): array {
                return [];
            }
            public function get_var(string $query): ?string {
                return null;
            }
            public function get_row(string $query, $output = 'OBJECT') {
                return null;
            }
        };

        $reviewService = new ReviewService();
        $this->schemaService = new SchemaService($reviewService);
        $this->schemaAdapter = new YoastSchemaAdapter($this->schemaService);
        $this->seeder = new YoastSeoSeeder();
        $this->observer = new AutoSeoObserver($this->seeder);
    }

    public function testYoastSchemaAdapterWiresProductAndWebPageGraph(): void
    {
        $postId = 101;
        $post = new WP_Post();
        $post->ID = $postId;
        $post->post_title = 'Shoei RF-1400 Helmet';
        $post->post_name = 'shoei-rf-1400';
        $post->post_type = 'helmet';
        $post->post_status = 'publish';
        $GLOBALS['wp_mock_posts'][$postId] = $post;
        $GLOBALS['wp_mock_singular_post_type'] = 'helmet';
        $GLOBALS['wp_mock_queried_object_id'] = $postId;

        // Set helmet metadata
        $GLOBALS['wp_post_meta'][$postId] = [
            'price_retail_usd' => '579.99',
            'spec_weight_g' => '1550',
            'helmet_brand' => 'Shoei',
        ];

        $initialGraph = [
            [
                '@type' => 'WebSite',
                '@id'   => 'https://helmetsan.com/#website',
                'name'  => 'Helmetsan',
            ],
            [
                '@type'     => 'WebPage',
                '@id'       => 'https://helmetsan.com/helmets/shoei-rf-1400/#webpage',
                'url'       => 'https://helmetsan.com/helmets/shoei-rf-1400/',
                'isPartOf'  => ['@id' => 'https://helmetsan.com/#website'],
            ],
        ];

        $unifiedGraph = $this->schemaAdapter->filterSchemaGraph($initialGraph);

        // Verify Product and FAQPage nodes were appended into Yoast's @graph
        $this->assertCount(4, $unifiedGraph);
        $productNode = $unifiedGraph[2];
        $this->assertSame('Product', $productNode['@type']);
        $this->assertStringContainsString('#product', $productNode['@id']);
        $this->assertArrayNotHasKey('@context', $productNode, 'Child node in unified @graph should not have standalone @context');

        // Verify WebPage now has mainEntity pointing to the Product node
        $webPageNode = $unifiedGraph[1];
        $this->assertSame(['@id' => $productNode['@id']], $webPageNode['mainEntity']);

        // Verify FAQPage node was appended for GEO (Generative Engine Optimization)
        $faqNode = $unifiedGraph[3];
        $this->assertSame('FAQPage', $faqNode['@type']);
        $this->assertStringContainsString('#faq', $faqNode['@id']);
        $this->assertSame(['@id' => $webPageNode['@id']], $faqNode['isPartOf']);
    }

    public function testEditorialLockedPreventsOverwritingHumanAuthoredSeo(): void
    {
        $postId = 202;
        $post = new WP_Post();
        $post->ID = $postId;
        $post->post_title = 'Arai Corsair-X';
        $post->post_name = 'arai-corsair-x';
        $post->post_type = 'helmet';
        $GLOBALS['wp_mock_posts'][$postId] = $post;

        // Human editor authored specific title and description in Yoast metabox
        $GLOBALS['wp_post_meta'][$postId] = [
            YoastSeoSeeder::YOAST_TITLE    => 'Arai Corsair-X Expert Track Review | Helmetsan',
            YoastSeoSeeder::YOAST_METADESC => 'Custom human-crafted editorial description that should never be deleted.',
            // Note: PROVENANCE_META is empty (not generated by programmatic AI seeder)
        ];

        // Should detect editorial lock
        $this->assertTrue($this->seeder->isEditorialLocked($postId));

        // Programmatic seedSinglePost must refuse to overwrite
        $seeded = $this->seeder->seedSinglePost($postId, false);
        $this->assertFalse($seeded);
        $this->assertSame('Arai Corsair-X Expert Track Review | Helmetsan', $GLOBALS['wp_post_meta'][$postId][YoastSeoSeeder::YOAST_TITLE]);
    }

    public function testProgrammaticSeederOverwritesWhenPreviouslyGenerated(): void
    {
        $postId = 203;
        $post = new WP_Post();
        $post->ID = $postId;
        $post->post_title = 'AGV Pista GP RR';
        $post->post_name = 'agv-pista-gp-rr';
        $post->post_type = 'helmet';
        $GLOBALS['wp_mock_posts'][$postId] = $post;

        // Post has previously generated SEO meta
        $GLOBALS['wp_post_meta'][$postId] = [
            YoastSeoSeeder::YOAST_TITLE    => 'Old Auto Title',
            YoastSeoSeeder::YOAST_METADESC => 'Old Auto Meta Description',
            YoastSeoSeeder::PROVENANCE_META => YoastSeoSeeder::PROVENANCE_GENERATED,
        ];

        // Should NOT be locked
        $this->assertFalse($this->seeder->isEditorialLocked($postId));

        // Seeding updates with fresh template
        $seeded = $this->seeder->seedSinglePost($postId, false);
        $this->assertTrue($seeded);
        $this->assertStringContainsString('AGV Pista GP RR', $GLOBALS['wp_post_meta'][$postId][YoastSeoSeeder::YOAST_TITLE]);
        $this->assertSame(YoastSeoSeeder::PROVENANCE_GENERATED, $GLOBALS['wp_post_meta'][$postId][YoastSeoSeeder::PROVENANCE_META]);
    }

    public function testYoastOpenGraphImageFallsBackToGalleryImage(): void
    {
        $postId = 301;
        $GLOBALS['wp_mock_singular_post_type'] = 'helmet';
        $GLOBALS['wp_mock_queried_object_id'] = $postId;
        $GLOBALS['wp_mock_has_thumbnail'][$postId] = false;

        $galleryUrl = 'https://cdn.helmetsan.com/images/shoei-rf-1400-front.webp';
        $GLOBALS['wp_post_meta'][$postId] = [
            'gallery_images' => [$galleryUrl, 'https://cdn.helmetsan.com/images/shoei-rf-1400-side.webp'],
        ];

        $ogImage = $this->observer->filterYoastOpenGraphImage('https://helmetsan.com/default-og.jpg');
        $this->assertSame($galleryUrl, $ogImage);
    }
}
