# Memory
maxmemory 789mb
maxmemory-policy allkeys-lru
lazyfree-lazy-eviction yes

# Databases
databases 16

# Security
requirepass 636hTupeqNsyEIBRdHnqM6q39WmDqJ6K0c6or2KWYRfP2HCY
bind 127.0.0.1
protected-mode yes
port 6379

# Performance
timeout 0

# Persistence (disabled for cache)
save ""
appendonly no

# Logging
loglevel notice
logfile /var/log/redis/redis-server.log
unixsocket /var/run/redis/redis-server.sock
unixsocketperm 770
